"""Added password_resets table

Revision ID: 3e82154ac8c4
Revises: c4769ed3619e
Create Date: 2020-05-16 01:55:54.085455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e82154ac8c4'
down_revision = 'c4769ed3619e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('reset_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_key')
    )
    op.create_unique_constraint(None, 'registration_profile', ['activation_key'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'registration_profile', type_='unique')
    op.drop_table('password_reset')
    # ### end Alembic commands ###
