"""Add user_id to company

Revision ID: 6a35f68dbe01
Revises: b71e9f5544ae
Create Date: 2020-05-21 04:32:26.944645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a35f68dbe01'
down_revision = 'b71e9f5544ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'companies', ['id'])
    op.create_unique_constraint(None, 'companies', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'user_id')
    # ### end Alembic commands ###
