"""Create resume related models

Revision ID: a4479dae5949
Revises: f4bc57f377bf
Create Date: 2020-05-22 12:24:19.753905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4479dae5949'
down_revision = 'f4bc57f377bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('award', sa.String(length=120), nullable=False),
    sa.Column('education_type_id', sa.Integer(), nullable=False),
    sa.Column('program_length', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('linkedin_url', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('linkedin_url'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('skills', sa.String(length=120), nullable=True),
    sa.Column('experience_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experiences')
    op.drop_table('profiles')
    op.drop_table('education')
    # ### end Alembic commands ###
